### ISSUE TITLE
A little doubt

### ISSUE THREAD

**Issue by zhangxjohn** [siyuyuan/analogykb#1]
in dataset, `['humans', 'run', 'a dog'], 1215.1239999999993]`,
where,  what does  `1215.1239999999993` mean?

**Comment by siyuyuan** [comment]
> in dataset, `['humans', 'run', 'a dog'], 1215.1239999999993]`, where, what does `1215.1239999999993` mean?

Thanks for your asking! To make our analogy KB more applicable to real-world scenarios, we rank the concept pairs according to their popularity scores, reflected by pageview times (in wikidata) and concept weights (in conceptnet). Thus the number means the pageview (wikidata) and weight (conceptnet).

**Comment by zhangxjohn** [comment]
Thank you.
